[package]
name = "slime"
version = "0.1.0"
edition = "2021"

[dependencies]
rustyline = "11.0.0" ## Repl support.
thiserror = "1.0.39" ## Error handling.
clap      = { version = "4.2.0", features = ["derive"] } ## Commandline argument parser.
pest      = "2.0"
pest_derive = "2.0"
